USE [master]
GO

EXEC msdb.dbo.sp_delete_database_backuphistory @database_name = N'Ecommerce'
GO

USE [master]
GO
ALTER DATABASE [Ecommerce] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
USE [master]
GO
/****** Object:  Database [Ecommerce]    Script Date: 24.06.2015 15:10:21 ******/
DROP DATABASE [Ecommerce]
GO



/****** Object:  Database [Ecommerce]    Script Date: 24.06.2015 14:32:13 ******/
CREATE DATABASE [Ecommerce]
GO

ALTER DATABASE Ecommerce COLLATE Latin1_General_CI_AS;
GO

ALTER DATABASE [Ecommerce] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Ecommerce].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Ecommerce] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [Ecommerce] SET ANSI_NULLS OFF
GO

ALTER DATABASE [Ecommerce] SET ANSI_PADDING OFF
GO

ALTER DATABASE [Ecommerce] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [Ecommerce] SET ARITHABORT OFF
GO

ALTER DATABASE [Ecommerce] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [Ecommerce] SET AUTO_CREATE_STATISTICS ON
GO

ALTER DATABASE [Ecommerce] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [Ecommerce] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [Ecommerce] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [Ecommerce] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [Ecommerce] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [Ecommerce] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [Ecommerce] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [Ecommerce] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [Ecommerce] SET  DISABLE_BROKER
GO

ALTER DATABASE [Ecommerce] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [Ecommerce] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [Ecommerce] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [Ecommerce] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [Ecommerce] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [Ecommerce] SET READ_COMMITTED_SNAPSHOT ON
GO

ALTER DATABASE [Ecommerce] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [Ecommerce] SET RECOVERY SIMPLE
GO

ALTER DATABASE [Ecommerce] SET  MULTI_USER
GO

ALTER DATABASE [Ecommerce] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [Ecommerce] SET DB_CHAINING OFF
GO

ALTER DATABASE [Ecommerce] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [Ecommerce] SET TARGET_RECOVERY_TIME = 0 SECONDS
GO

ALTER DATABASE [Ecommerce] SET  READ_WRITE
GO


-- Login
USE [master]
GO

/* For security reasons the login is created disabled and with a random password. */
/****** Object:  Login [dataSource.username]    Script Date: 24.06.2015 14:36:00 ******/
DROP LOGIN [Ecommerce_App_User]
GO

CREATE LOGIN [Ecommerce_App_User] WITH PASSWORD=N'eco_20', DEFAULT_DATABASE=[Ecommerce], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

-- Login
USE [Ecommerce]
GO


-- User
IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'Ecommerce_App_User')
CREATE USER [Ecommerce_App_User] FOR LOGIN [Ecommerce_App_User] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [Ecommerce_App_User]
GO
